### ISSUE TITLE
Multi-Threading-Support bei der Suche nach Refinements

### ISSUE THREAD

**Issue by mrapp-ke** [mrapp-ke/MLRL-Boomer#147]
Aktuell verwendet der komplette Lernalgorithmus nur einen einzigen Thread. Die Suche nach dem besten Refinement einer Regel könnte jedoch mit Hilfe mehrerer CPU-Threads beschleunigt werden, indem die möglichen Refinements für jedes Feature parallel gesucht werden. Um dies zu ermöglichen, müssen folgende Vorraussetzungen erfüllt sein:

- [x] Die `Loss`-Klasse muss es erlauben mehrere Suchen parallel auszuführen (siehe #145)
- [x] Es muss auf jegliche Python-Interaktionen im entsprechenden Code verzichtet werden (siehe #146)
- [x] Die Funktion `find_head` muss über ein separates Argument zur Angabe eines überschreibbaren `HeadCandidate`-Objekts verfügen (siehe #166)
- [x] Die Abfrage ob ein Feature nominal ist muss unabhängig von den anderen Features erfolgen können (siehe #216)
- [x] Aufrufe von BLAS' DSPMV- und LAPACK's DSYSV-Routine sind aktuell nicht thread-safe (siehe #219)
