### ISSUE TITLE
Sparse Repräsentation der Gradienten und Hessians

### ISSUE THREAD

**Issue by mrapp-ke** [mrapp-ke/MLRL-Boomer#148]
Bisher werden die Gradienten und Hessians in (zweidimensionalen) Arrays gespeichert. Um in Zukunft sehr große Datensätze 
handhaben zu können, ist die (optionale) Unterstützung von sparsen Datenstrukturen notwendig. Dazu eignet sich das LIL-Format, bei dem die Gradienten/Hessians jedes Trainingsbeispiels als eine (Single-)Linked-List gespeichert werden.

Es bestehen folgende Voraussetzung für die Umsetzung dieser Funktionalität:

* [x] Die Speicherung von Statistiken, d.h. der Gradienten und Hessians, muss getrennt von der Loss-Implementierung erfolgen (siehe #167)
* [x] Abstraktionen von Vektoren und Matrizen, die unabhängig von der Speicherung der Elemente verwendbare Funktionen anbieten und statt einer konkreten Datenstruktur für die Speicherung der Gradienten/Hessians verwendet werden (siehe #245)
* ~~Die Funktion `addToSubset` der Klasse `IStatisticsSubset` muss einen `bool`-Wert zurück gegeben der angibt, ob das Subset verändert wurde und demzufolge eine Bedingung überprüft werden muss~~ (siehe #314)
* [x] Die Funktionen, die für die Berechnung von Vorhersagen und für deren Bewertung zuständig sind, müssen im Fall von sparsen Gradienten und Hessians eine Datenstruktur zurückgeben, die die verwendeten Label-Indizes speichert. Diese Indizes müssen von Implementierungen der Klasse `IHeadRefinement` berücksichtigt werden (siehe #320)
* ~~Die Datenstrukturen zum Speichern von Statistiken in Vektoren müssen den Zugriff auf die dazugehörigen Label-Indizes erlauben~~ (siehe #329)

Zur Umsetzung sind zusätzlich folgende Dinge notwendig:

* Implementierung sparser Datenstrukturen, die die oben genannten Abstraktionen umsetzen
* Datenstruktur um Ground-Truth-Labels in einer sparsen CSR-Matrix zu speichern
* Erstellen einer Factory um Statistiken, die mit Hilfe der sparsen Datenstrukturen gespeichert werden, auf Basis einer CSR-Label-Matrix zu erzeugen
